services:
  - type: web
    name: shaadisetgo-backend
    env: node
    buildCommand: npm install && npm install axios
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://shaadisetgo.vercel.app
    healthCheckPath: /health
    autoDeploy: true 